name: Build-Kernel-N

on:
  workflow_dispatch:

run-name: Build kernel

jobs:
  kernel:
    runs-on: ubuntu-22.04
    name: Build kernel 
    steps:
      - name: Checkout Joshua-Riek repo
        uses: actions/checkout@v4
        with:
          repository: Joshua-Riek/linux-rockchip
          ref: noble
          path: joshua-repo
          fetch-depth: 2

      - name: Merge files
        run: |
          mkdir temp
          cp -rvf joshua-repo/debian* temp/
          tar -zcvf debian.tar.gz temp/

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
            name: joshua-debian
            path: ./debian.tar.gz
            if-no-files-found: error
